apiVersion: apps/v1
kind: Deployment # Modificar a StatefulSet (aplicacion con persistencia debido a los resultados que devuelve)
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: nfs-spark-driver
          nfs:
            server: 10.0.0.250
            path: /NFS/data
      containers:
      - name: backend
        image: pierresimt/backend-cn
        imagePullPolicy: Always
        volumeMounts:
          - name: nfs-spark-driver
            mountPath: "/usr/src/app/Archivos"
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /api/Get/Methods
            port: 3000
        livenessProbe:
          httpGet:
            path: /api/Get/Methods
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
    selector:
      app: backend
 