apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: graph-cloud
spec:
    rules:
    - http:
        paths: 
        - path: /*
          backend:
            serviceName: frontend
            servicePort: 4100
        - path: /api/*
          backend:
            serviceName: backend
            servicePort: 3000   
